---
blank_issues_enabled: false
contact_links:
  - name: poseidon-rs Community Support
    url: https://github.com/keep-starknet-strange/poseidon-rs/discussions
    about: Please ask and answer questions here.
